timezone: DE
encoding: utf-8
highlighter: rouge

index_post_capacity: 5
nav:
  - name: INDEX
    url: index.html
  - name: ARCHIVE
    url: archive.html
  - name: TAGS
    url: tags.html
  - name: IMPRESSUM
    url: impressum.html

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  style: "expanded"
  sass_dir: "_sass"
