timezone: DE
encoding: utf-8
highlighter: rouge

index_post_capacity: 5
nav:
  - name: Index
    url: /
  - name: Archive
    url: /archive.html
  - name: Tags
    url: /tags.html
  - name: Imprint
    url: /impressum.html

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  style: "expanded"
  sass_dir: "_sass"
