timezone: DE
encoding: utf-8
highlighter: rouge

index_post_capacity: 5
nav: [ index , tags , archive , impressum ]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  style: "expanded"
  sass_dir: "_sass"
